// automatically generated by the FlatBuffers compiler, do not modify
// @generated

use crate::game_common_generated::*;
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod rand_game {

  use crate::game_common_generated::*;
extern crate alloc;

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_ACTION_KIND: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_ACTION_KIND: i8 = 6;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_ACTION_KIND: [ActionKind; 7] = [
  ActionKind::Move,
  ActionKind::Mine,
  ActionKind::Build,
  ActionKind::Lift,
  ActionKind::Put,
  ActionKind::Craft,
  ActionKind::Research,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct ActionKind(pub i8);
#[allow(non_upper_case_globals)]
impl ActionKind {
  pub const Move: Self = Self(0);
  pub const Mine: Self = Self(1);
  pub const Build: Self = Self(2);
  pub const Lift: Self = Self(3);
  pub const Put: Self = Self(4);
  pub const Craft: Self = Self(5);
  pub const Research: Self = Self(6);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 6;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Move,
    Self::Mine,
    Self::Build,
    Self::Lift,
    Self::Put,
    Self::Craft,
    Self::Research,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Move => Some("Move"),
      Self::Mine => Some("Mine"),
      Self::Build => Some("Build"),
      Self::Lift => Some("Lift"),
      Self::Put => Some("Put"),
      Self::Craft => Some("Craft"),
      Self::Research => Some("Research"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for ActionKind {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for ActionKind {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for ActionKind {
    type Output = ActionKind;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for ActionKind {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for ActionKind {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    i8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for ActionKind {}
pub enum ActionOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Action<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Action<'a> {
  type Inner = Action<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Action<'a> {
  pub const VT_KIND: ::flatbuffers::VOffsetT = 4;
  pub const VT_ACTOR_ENTITY_ID: ::flatbuffers::VOffsetT = 6;
  pub const VT_TARGET_ENTITY_ID: ::flatbuffers::VOffsetT = 8;
  pub const VT_TARGET_BUILDING_ID: ::flatbuffers::VOffsetT = 10;
  pub const VT_TARGET_POSITION: ::flatbuffers::VOffsetT = 12;
  pub const VT_RESOURCE: ::flatbuffers::VOffsetT = 14;
  pub const VT_BUILDING_KIND: ::flatbuffers::VOffsetT = 16;
  pub const VT_AMOUNT: ::flatbuffers::VOffsetT = 18;
  pub const VT_RECIPE_ID: ::flatbuffers::VOffsetT = 20;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Action { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ActionArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Action<'bldr>> {
    let mut builder = ActionBuilder::new(_fbb);
    builder.add_target_building_id(args.target_building_id);
    builder.add_target_entity_id(args.target_entity_id);
    builder.add_actor_entity_id(args.actor_entity_id);
    if let Some(x) = args.recipe_id { builder.add_recipe_id(x); }
    builder.add_amount(args.amount);
    if let Some(x) = args.resource { builder.add_resource(x); }
    if let Some(x) = args.target_position { builder.add_target_position(x); }
    builder.add_building_kind(args.building_kind);
    builder.add_kind(args.kind);
    builder.finish()
  }


  #[inline]
  pub fn kind(&self) -> ActionKind {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<ActionKind>(Action::VT_KIND, Some(ActionKind::Move)).unwrap()}
  }
  #[inline]
  pub fn actor_entity_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Action::VT_ACTOR_ENTITY_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn target_entity_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Action::VT_TARGET_ENTITY_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn target_building_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Action::VT_TARGET_BUILDING_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn target_position(&self) -> Option<&'a Vec2I> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Vec2I>(Action::VT_TARGET_POSITION, None)}
  }
  #[inline]
  pub fn resource(&self) -> Option<&'a ResourceStack> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<ResourceStack>(Action::VT_RESOURCE, None)}
  }
  #[inline]
  pub fn building_kind(&self) -> BuildingKind {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<BuildingKind>(Action::VT_BUILDING_KIND, Some(BuildingKind::None)).unwrap()}
  }
  #[inline]
  pub fn amount(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Action::VT_AMOUNT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn recipe_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Action::VT_RECIPE_ID, None)}
  }
}

impl ::flatbuffers::Verifiable for Action<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<ActionKind>("kind", Self::VT_KIND, false)?
     .visit_field::<u64>("actor_entity_id", Self::VT_ACTOR_ENTITY_ID, false)?
     .visit_field::<u64>("target_entity_id", Self::VT_TARGET_ENTITY_ID, false)?
     .visit_field::<u64>("target_building_id", Self::VT_TARGET_BUILDING_ID, false)?
     .visit_field::<Vec2I>("target_position", Self::VT_TARGET_POSITION, false)?
     .visit_field::<ResourceStack>("resource", Self::VT_RESOURCE, false)?
     .visit_field::<BuildingKind>("building_kind", Self::VT_BUILDING_KIND, false)?
     .visit_field::<u32>("amount", Self::VT_AMOUNT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("recipe_id", Self::VT_RECIPE_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct ActionArgs<'a> {
    pub kind: ActionKind,
    pub actor_entity_id: u64,
    pub target_entity_id: u64,
    pub target_building_id: u64,
    pub target_position: Option<&'a Vec2I>,
    pub resource: Option<&'a ResourceStack>,
    pub building_kind: BuildingKind,
    pub amount: u32,
    pub recipe_id: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for ActionArgs<'a> {
  #[inline]
  fn default() -> Self {
    ActionArgs {
      kind: ActionKind::Move,
      actor_entity_id: 0,
      target_entity_id: 0,
      target_building_id: 0,
      target_position: None,
      resource: None,
      building_kind: BuildingKind::None,
      amount: 0,
      recipe_id: None,
    }
  }
}

pub struct ActionBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ActionBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_kind(&mut self, kind: ActionKind) {
    self.fbb_.push_slot::<ActionKind>(Action::VT_KIND, kind, ActionKind::Move);
  }
  #[inline]
  pub fn add_actor_entity_id(&mut self, actor_entity_id: u64) {
    self.fbb_.push_slot::<u64>(Action::VT_ACTOR_ENTITY_ID, actor_entity_id, 0);
  }
  #[inline]
  pub fn add_target_entity_id(&mut self, target_entity_id: u64) {
    self.fbb_.push_slot::<u64>(Action::VT_TARGET_ENTITY_ID, target_entity_id, 0);
  }
  #[inline]
  pub fn add_target_building_id(&mut self, target_building_id: u64) {
    self.fbb_.push_slot::<u64>(Action::VT_TARGET_BUILDING_ID, target_building_id, 0);
  }
  #[inline]
  pub fn add_target_position(&mut self, target_position: &Vec2I) {
    self.fbb_.push_slot_always::<&Vec2I>(Action::VT_TARGET_POSITION, target_position);
  }
  #[inline]
  pub fn add_resource(&mut self, resource: &ResourceStack) {
    self.fbb_.push_slot_always::<&ResourceStack>(Action::VT_RESOURCE, resource);
  }
  #[inline]
  pub fn add_building_kind(&mut self, building_kind: BuildingKind) {
    self.fbb_.push_slot::<BuildingKind>(Action::VT_BUILDING_KIND, building_kind, BuildingKind::None);
  }
  #[inline]
  pub fn add_amount(&mut self, amount: u32) {
    self.fbb_.push_slot::<u32>(Action::VT_AMOUNT, amount, 0);
  }
  #[inline]
  pub fn add_recipe_id(&mut self, recipe_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Action::VT_RECIPE_ID, recipe_id);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ActionBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ActionBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Action<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Action<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Action");
      ds.field("kind", &self.kind());
      ds.field("actor_entity_id", &self.actor_entity_id());
      ds.field("target_entity_id", &self.target_entity_id());
      ds.field("target_building_id", &self.target_building_id());
      ds.field("target_position", &self.target_position());
      ds.field("resource", &self.resource());
      ds.field("building_kind", &self.building_kind());
      ds.field("amount", &self.amount());
      ds.field("recipe_id", &self.recipe_id());
      ds.finish()
  }
}
pub enum GameOutputOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct GameOutput<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for GameOutput<'a> {
  type Inner = GameOutput<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> GameOutput<'a> {
  pub const VT_PROTOCOL_VERSION: ::flatbuffers::VOffsetT = 4;
  pub const VT_ACTIONS: ::flatbuffers::VOffsetT = 6;
  pub const VT_PERSISTENT_MEMORY: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    GameOutput { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args GameOutputArgs<'args>
  ) -> ::flatbuffers::WIPOffset<GameOutput<'bldr>> {
    let mut builder = GameOutputBuilder::new(_fbb);
    if let Some(x) = args.persistent_memory { builder.add_persistent_memory(x); }
    if let Some(x) = args.actions { builder.add_actions(x); }
    builder.add_protocol_version(args.protocol_version);
    builder.finish()
  }


  #[inline]
  pub fn protocol_version(&self) -> ProtocolVersion {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<ProtocolVersion>(GameOutput::VT_PROTOCOL_VERSION, Some(ProtocolVersion::V1)).unwrap()}
  }
  #[inline]
  pub fn actions(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Action<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Action>>>>(GameOutput::VT_ACTIONS, None)}
  }
  #[inline]
  pub fn persistent_memory(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(GameOutput::VT_PERSISTENT_MEMORY, None)}
  }
}

impl ::flatbuffers::Verifiable for GameOutput<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<ProtocolVersion>("protocol_version", Self::VT_PROTOCOL_VERSION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Action>>>>("actions", Self::VT_ACTIONS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("persistent_memory", Self::VT_PERSISTENT_MEMORY, false)?
     .finish();
    Ok(())
  }
}
pub struct GameOutputArgs<'a> {
    pub protocol_version: ProtocolVersion,
    pub actions: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Action<'a>>>>>,
    pub persistent_memory: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for GameOutputArgs<'a> {
  #[inline]
  fn default() -> Self {
    GameOutputArgs {
      protocol_version: ProtocolVersion::V1,
      actions: None,
      persistent_memory: None,
    }
  }
}

pub struct GameOutputBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> GameOutputBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_protocol_version(&mut self, protocol_version: ProtocolVersion) {
    self.fbb_.push_slot::<ProtocolVersion>(GameOutput::VT_PROTOCOL_VERSION, protocol_version, ProtocolVersion::V1);
  }
  #[inline]
  pub fn add_actions(&mut self, actions: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Action<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(GameOutput::VT_ACTIONS, actions);
  }
  #[inline]
  pub fn add_persistent_memory(&mut self, persistent_memory: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(GameOutput::VT_PERSISTENT_MEMORY, persistent_memory);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> GameOutputBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    GameOutputBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<GameOutput<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for GameOutput<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("GameOutput");
      ds.field("protocol_version", &self.protocol_version());
      ds.field("actions", &self.actions());
      ds.field("persistent_memory", &self.persistent_memory());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `GameOutput`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_game_output_unchecked`.
pub fn root_as_game_output(buf: &[u8]) -> Result<GameOutput<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<GameOutput>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `GameOutput` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_game_output_unchecked`.
pub fn size_prefixed_root_as_game_output(buf: &[u8]) -> Result<GameOutput<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<GameOutput>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `GameOutput` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_game_output_unchecked`.
pub fn root_as_game_output_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<GameOutput<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<GameOutput<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `GameOutput` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_game_output_unchecked`.
pub fn size_prefixed_root_as_game_output_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<GameOutput<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<GameOutput<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a GameOutput and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `GameOutput`.
pub unsafe fn root_as_game_output_unchecked(buf: &[u8]) -> GameOutput<'_> {
  unsafe { ::flatbuffers::root_unchecked::<GameOutput>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed GameOutput and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `GameOutput`.
pub unsafe fn size_prefixed_root_as_game_output_unchecked(buf: &[u8]) -> GameOutput<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<GameOutput>(buf) }
}
pub const GAME_OUTPUT_IDENTIFIER: &str = "BWO1";

#[inline]
pub fn game_output_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, GAME_OUTPUT_IDENTIFIER, false)
}

#[inline]
pub fn game_output_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, GAME_OUTPUT_IDENTIFIER, true)
}

#[inline]
pub fn finish_game_output_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<GameOutput<'a>>) {
  fbb.finish(root, Some(GAME_OUTPUT_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_game_output_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<GameOutput<'a>>) {
  fbb.finish_size_prefixed(root, Some(GAME_OUTPUT_IDENTIFIER));
}
}  // pub mod RandGame

