// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod rand_game {

extern crate alloc;

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_PROTOCOL_VERSION: u16 = 1;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_PROTOCOL_VERSION: u16 = 1;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_PROTOCOL_VERSION: [ProtocolVersion; 1] = [
  ProtocolVersion::V1,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct ProtocolVersion(pub u16);
#[allow(non_upper_case_globals)]
impl ProtocolVersion {
  pub const V1: Self = Self(1);

  pub const ENUM_MIN: u16 = 1;
  pub const ENUM_MAX: u16 = 1;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::V1,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::V1 => Some("V1"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for ProtocolVersion {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for ProtocolVersion {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u16>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for ProtocolVersion {
    type Output = ProtocolVersion;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u16>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for ProtocolVersion {
  type Scalar = u16;
  #[inline]
  fn to_little_endian(self) -> u16 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u16) -> Self {
    let b = u16::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for ProtocolVersion {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u16::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for ProtocolVersion {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_MAP_KIND: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_MAP_KIND: i8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_MAP_KIND: [MapKind; 3] = [
  MapKind::Resource,
  MapKind::Hazard,
  MapKind::Monster,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct MapKind(pub i8);
#[allow(non_upper_case_globals)]
impl MapKind {
  pub const Resource: Self = Self(0);
  pub const Hazard: Self = Self(1);
  pub const Monster: Self = Self(2);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Resource,
    Self::Hazard,
    Self::Monster,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Resource => Some("Resource"),
      Self::Hazard => Some("Hazard"),
      Self::Monster => Some("Monster"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for MapKind {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for MapKind {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for MapKind {
    type Output = MapKind;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for MapKind {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for MapKind {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    i8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for MapKind {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_RESOURCE_KIND: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_RESOURCE_KIND: i8 = 6;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_RESOURCE_KIND: [ResourceKind; 7] = [
  ResourceKind::None,
  ResourceKind::Iron,
  ResourceKind::Copper,
  ResourceKind::Energy,
  ResourceKind::Stone,
  ResourceKind::Tree,
  ResourceKind::Water,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct ResourceKind(pub i8);
#[allow(non_upper_case_globals)]
impl ResourceKind {
  pub const None: Self = Self(0);
  pub const Iron: Self = Self(1);
  pub const Copper: Self = Self(2);
  pub const Energy: Self = Self(3);
  pub const Stone: Self = Self(4);
  pub const Tree: Self = Self(5);
  pub const Water: Self = Self(6);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 6;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::None,
    Self::Iron,
    Self::Copper,
    Self::Energy,
    Self::Stone,
    Self::Tree,
    Self::Water,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::None => Some("None"),
      Self::Iron => Some("Iron"),
      Self::Copper => Some("Copper"),
      Self::Energy => Some("Energy"),
      Self::Stone => Some("Stone"),
      Self::Tree => Some("Tree"),
      Self::Water => Some("Water"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for ResourceKind {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for ResourceKind {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for ResourceKind {
    type Output = ResourceKind;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for ResourceKind {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for ResourceKind {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    i8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for ResourceKind {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_BUILDING_KIND: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_BUILDING_KIND: i8 = 5;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_BUILDING_KIND: [BuildingKind; 6] = [
  BuildingKind::None,
  BuildingKind::Miner,
  BuildingKind::Storage,
  BuildingKind::Solar,
  BuildingKind::Assembler,
  BuildingKind::Furnace,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct BuildingKind(pub i8);
#[allow(non_upper_case_globals)]
impl BuildingKind {
  pub const None: Self = Self(0);
  pub const Miner: Self = Self(1);
  pub const Storage: Self = Self(2);
  pub const Solar: Self = Self(3);
  pub const Assembler: Self = Self(4);
  pub const Furnace: Self = Self(5);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 5;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::None,
    Self::Miner,
    Self::Storage,
    Self::Solar,
    Self::Assembler,
    Self::Furnace,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::None => Some("None"),
      Self::Miner => Some("Miner"),
      Self::Storage => Some("Storage"),
      Self::Solar => Some("Solar"),
      Self::Assembler => Some("Assembler"),
      Self::Furnace => Some("Furnace"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for BuildingKind {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for BuildingKind {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for BuildingKind {
    type Output = BuildingKind;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for BuildingKind {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for BuildingKind {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    i8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for BuildingKind {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_ENTITY_KIND: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_ENTITY_KIND: i8 = 6;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_ENTITY_KIND: [EntityKind; 7] = [
  EntityKind::Core,
  EntityKind::Worker,
  EntityKind::Miner,
  EntityKind::Storage,
  EntityKind::Solar,
  EntityKind::Relay,
  EntityKind::Decoy,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct EntityKind(pub i8);
#[allow(non_upper_case_globals)]
impl EntityKind {
  pub const Core: Self = Self(0);
  pub const Worker: Self = Self(1);
  pub const Miner: Self = Self(2);
  pub const Storage: Self = Self(3);
  pub const Solar: Self = Self(4);
  pub const Relay: Self = Self(5);
  pub const Decoy: Self = Self(6);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 6;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Core,
    Self::Worker,
    Self::Miner,
    Self::Storage,
    Self::Solar,
    Self::Relay,
    Self::Decoy,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Core => Some("Core"),
      Self::Worker => Some("Worker"),
      Self::Miner => Some("Miner"),
      Self::Storage => Some("Storage"),
      Self::Solar => Some("Solar"),
      Self::Relay => Some("Relay"),
      Self::Decoy => Some("Decoy"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for EntityKind {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for EntityKind {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for EntityKind {
    type Output = EntityKind;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for EntityKind {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for EntityKind {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    i8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for EntityKind {}
// struct Vec2I, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Vec2I(pub [u8; 8]);
impl Default for Vec2I { 
  fn default() -> Self { 
    Self([0; 8])
  }
}
impl ::core::fmt::Debug for Vec2I {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    f.debug_struct("Vec2I")
      .field("x", &self.x())
      .field("y", &self.y())
      .finish()
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Vec2I {}
impl<'a> ::flatbuffers::Follow<'a> for Vec2I {
  type Inner = &'a Vec2I;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { <&'a Vec2I>::follow(buf, loc) }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for &'a Vec2I {
  type Inner = &'a Vec2I;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { ::flatbuffers::follow_cast_ref::<Vec2I>(buf, loc) }
  }
}
impl<'b> ::flatbuffers::Push for Vec2I {
    type Output = Vec2I;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const Vec2I as *const u8, <Self as ::flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> ::flatbuffers::PushAlignment {
        ::flatbuffers::PushAlignment::new(4)
    }
}

impl<'a> ::flatbuffers::Verifiable for Vec2I {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Vec2I {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    x: i32,
    y: i32,
  ) -> Self {
    let mut s = Self([0; 8]);
    s.set_x(x);
    s.set_y(y);
    s
  }

  pub fn x(&self) -> i32 {
    let mut mem = ::core::mem::MaybeUninit::<<i32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<i32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_x(&mut self, x: i32) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        ::core::mem::size_of::<<i32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn y(&self) -> i32 {
    let mut mem = ::core::mem::MaybeUninit::<<i32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[4..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<i32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_y(&mut self, x: i32) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[4..].as_mut_ptr(),
        ::core::mem::size_of::<<i32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

}

// struct ChunkCoord, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct ChunkCoord(pub [u8; 8]);
impl Default for ChunkCoord { 
  fn default() -> Self { 
    Self([0; 8])
  }
}
impl ::core::fmt::Debug for ChunkCoord {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    f.debug_struct("ChunkCoord")
      .field("x", &self.x())
      .field("y", &self.y())
      .finish()
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for ChunkCoord {}
impl<'a> ::flatbuffers::Follow<'a> for ChunkCoord {
  type Inner = &'a ChunkCoord;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { <&'a ChunkCoord>::follow(buf, loc) }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for &'a ChunkCoord {
  type Inner = &'a ChunkCoord;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { ::flatbuffers::follow_cast_ref::<ChunkCoord>(buf, loc) }
  }
}
impl<'b> ::flatbuffers::Push for ChunkCoord {
    type Output = ChunkCoord;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const ChunkCoord as *const u8, <Self as ::flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> ::flatbuffers::PushAlignment {
        ::flatbuffers::PushAlignment::new(4)
    }
}

impl<'a> ::flatbuffers::Verifiable for ChunkCoord {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> ChunkCoord {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    x: i32,
    y: i32,
  ) -> Self {
    let mut s = Self([0; 8]);
    s.set_x(x);
    s.set_y(y);
    s
  }

  pub fn x(&self) -> i32 {
    let mut mem = ::core::mem::MaybeUninit::<<i32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<i32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_x(&mut self, x: i32) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        ::core::mem::size_of::<<i32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn y(&self) -> i32 {
    let mut mem = ::core::mem::MaybeUninit::<<i32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[4..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<i32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_y(&mut self, x: i32) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[4..].as_mut_ptr(),
        ::core::mem::size_of::<<i32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

}

// struct ResourceStack, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct ResourceStack(pub [u8; 8]);
impl Default for ResourceStack { 
  fn default() -> Self { 
    Self([0; 8])
  }
}
impl ::core::fmt::Debug for ResourceStack {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    f.debug_struct("ResourceStack")
      .field("kind", &self.kind())
      .field("amount", &self.amount())
      .finish()
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for ResourceStack {}
impl<'a> ::flatbuffers::Follow<'a> for ResourceStack {
  type Inner = &'a ResourceStack;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { <&'a ResourceStack>::follow(buf, loc) }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for &'a ResourceStack {
  type Inner = &'a ResourceStack;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { ::flatbuffers::follow_cast_ref::<ResourceStack>(buf, loc) }
  }
}
impl<'b> ::flatbuffers::Push for ResourceStack {
    type Output = ResourceStack;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const ResourceStack as *const u8, <Self as ::flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> ::flatbuffers::PushAlignment {
        ::flatbuffers::PushAlignment::new(4)
    }
}

impl<'a> ::flatbuffers::Verifiable for ResourceStack {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> ResourceStack {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    kind: ResourceKind,
    amount: u32,
  ) -> Self {
    let mut s = Self([0; 8]);
    s.set_kind(kind);
    s.set_amount(amount);
    s
  }

  pub fn kind(&self) -> ResourceKind {
    let mut mem = ::core::mem::MaybeUninit::<<ResourceKind as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<ResourceKind as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_kind(&mut self, x: ResourceKind) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        ::core::mem::size_of::<<ResourceKind as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn amount(&self) -> u32 {
    let mut mem = ::core::mem::MaybeUninit::<<u32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[4..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_amount(&mut self, x: u32) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[4..].as_mut_ptr(),
        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

}

pub enum ItemStackOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ItemStack<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ItemStack<'a> {
  type Inner = ItemStack<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ItemStack<'a> {
  pub const VT_KIND: ::flatbuffers::VOffsetT = 4;
  pub const VT_AMOUNT: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ItemStack { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ItemStackArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ItemStack<'bldr>> {
    let mut builder = ItemStackBuilder::new(_fbb);
    builder.add_amount(args.amount);
    if let Some(x) = args.kind { builder.add_kind(x); }
    builder.finish()
  }


  #[inline]
  pub fn kind(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ItemStack::VT_KIND, None)}
  }
  #[inline]
  pub fn amount(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ItemStack::VT_AMOUNT, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for ItemStack<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("kind", Self::VT_KIND, false)?
     .visit_field::<u32>("amount", Self::VT_AMOUNT, false)?
     .finish();
    Ok(())
  }
}
pub struct ItemStackArgs<'a> {
    pub kind: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub amount: u32,
}
impl<'a> Default for ItemStackArgs<'a> {
  #[inline]
  fn default() -> Self {
    ItemStackArgs {
      kind: None,
      amount: 0,
    }
  }
}

pub struct ItemStackBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ItemStackBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_kind(&mut self, kind: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ItemStack::VT_KIND, kind);
  }
  #[inline]
  pub fn add_amount(&mut self, amount: u32) {
    self.fbb_.push_slot::<u32>(ItemStack::VT_AMOUNT, amount, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ItemStackBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ItemStackBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ItemStack<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ItemStack<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ItemStack");
      ds.field("kind", &self.kind());
      ds.field("amount", &self.amount());
      ds.finish()
  }
}
pub enum BuildingOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Building<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Building<'a> {
  type Inner = Building<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Building<'a> {
  pub const VT_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_KIND: ::flatbuffers::VOffsetT = 6;
  pub const VT_OWNER_ID: ::flatbuffers::VOffsetT = 8;
  pub const VT_POWER: ::flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Building { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args BuildingArgs
  ) -> ::flatbuffers::WIPOffset<Building<'bldr>> {
    let mut builder = BuildingBuilder::new(_fbb);
    builder.add_owner_id(args.owner_id);
    builder.add_id(args.id);
    builder.add_power(args.power);
    builder.add_kind(args.kind);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Building::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn kind(&self) -> BuildingKind {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<BuildingKind>(Building::VT_KIND, Some(BuildingKind::None)).unwrap()}
  }
  #[inline]
  pub fn owner_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Building::VT_OWNER_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn power(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Building::VT_POWER, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Building<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("id", Self::VT_ID, false)?
     .visit_field::<BuildingKind>("kind", Self::VT_KIND, false)?
     .visit_field::<u64>("owner_id", Self::VT_OWNER_ID, false)?
     .visit_field::<i32>("power", Self::VT_POWER, false)?
     .finish();
    Ok(())
  }
}
pub struct BuildingArgs {
    pub id: u64,
    pub kind: BuildingKind,
    pub owner_id: u64,
    pub power: i32,
}
impl<'a> Default for BuildingArgs {
  #[inline]
  fn default() -> Self {
    BuildingArgs {
      id: 0,
      kind: BuildingKind::None,
      owner_id: 0,
      power: 0,
    }
  }
}

pub struct BuildingBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> BuildingBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: u64) {
    self.fbb_.push_slot::<u64>(Building::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_kind(&mut self, kind: BuildingKind) {
    self.fbb_.push_slot::<BuildingKind>(Building::VT_KIND, kind, BuildingKind::None);
  }
  #[inline]
  pub fn add_owner_id(&mut self, owner_id: u64) {
    self.fbb_.push_slot::<u64>(Building::VT_OWNER_ID, owner_id, 0);
  }
  #[inline]
  pub fn add_power(&mut self, power: i32) {
    self.fbb_.push_slot::<i32>(Building::VT_POWER, power, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> BuildingBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    BuildingBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Building<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Building<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Building");
      ds.field("id", &self.id());
      ds.field("kind", &self.kind());
      ds.field("owner_id", &self.owner_id());
      ds.field("power", &self.power());
      ds.finish()
  }
}
pub enum TileOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Tile<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Tile<'a> {
  type Inner = Tile<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Tile<'a> {
  pub const VT_POSITION: ::flatbuffers::VOffsetT = 4;
  pub const VT_RESOURCE: ::flatbuffers::VOffsetT = 6;
  pub const VT_BUILDING: ::flatbuffers::VOffsetT = 8;
  pub const VT_OWNER_ID: ::flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Tile { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TileArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Tile<'bldr>> {
    let mut builder = TileBuilder::new(_fbb);
    builder.add_owner_id(args.owner_id);
    if let Some(x) = args.building { builder.add_building(x); }
    if let Some(x) = args.resource { builder.add_resource(x); }
    if let Some(x) = args.position { builder.add_position(x); }
    builder.finish()
  }


  #[inline]
  pub fn position(&self) -> Option<&'a Vec2I> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Vec2I>(Tile::VT_POSITION, None)}
  }
  #[inline]
  pub fn resource(&self) -> Option<&'a ResourceStack> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<ResourceStack>(Tile::VT_RESOURCE, None)}
  }
  #[inline]
  pub fn building(&self) -> Option<Building<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<Building>>(Tile::VT_BUILDING, None)}
  }
  #[inline]
  pub fn owner_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Tile::VT_OWNER_ID, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Tile<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<Vec2I>("position", Self::VT_POSITION, false)?
     .visit_field::<ResourceStack>("resource", Self::VT_RESOURCE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<Building>>("building", Self::VT_BUILDING, false)?
     .visit_field::<u64>("owner_id", Self::VT_OWNER_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct TileArgs<'a> {
    pub position: Option<&'a Vec2I>,
    pub resource: Option<&'a ResourceStack>,
    pub building: Option<::flatbuffers::WIPOffset<Building<'a>>>,
    pub owner_id: u64,
}
impl<'a> Default for TileArgs<'a> {
  #[inline]
  fn default() -> Self {
    TileArgs {
      position: None,
      resource: None,
      building: None,
      owner_id: 0,
    }
  }
}

pub struct TileBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> TileBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_position(&mut self, position: &Vec2I) {
    self.fbb_.push_slot_always::<&Vec2I>(Tile::VT_POSITION, position);
  }
  #[inline]
  pub fn add_resource(&mut self, resource: &ResourceStack) {
    self.fbb_.push_slot_always::<&ResourceStack>(Tile::VT_RESOURCE, resource);
  }
  #[inline]
  pub fn add_building(&mut self, building: ::flatbuffers::WIPOffset<Building<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<Building>>(Tile::VT_BUILDING, building);
  }
  #[inline]
  pub fn add_owner_id(&mut self, owner_id: u64) {
    self.fbb_.push_slot::<u64>(Tile::VT_OWNER_ID, owner_id, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> TileBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TileBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Tile<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Tile<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Tile");
      ds.field("position", &self.position());
      ds.field("resource", &self.resource());
      ds.field("building", &self.building());
      ds.field("owner_id", &self.owner_id());
      ds.finish()
  }
}
pub enum EntityOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Entity<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Entity<'a> {
  type Inner = Entity<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Entity<'a> {
  pub const VT_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_POSITION: ::flatbuffers::VOffsetT = 6;
  pub const VT_CARGO: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Entity { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args EntityArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Entity<'bldr>> {
    let mut builder = EntityBuilder::new(_fbb);
    builder.add_id(args.id);
    if let Some(x) = args.cargo { builder.add_cargo(x); }
    if let Some(x) = args.position { builder.add_position(x); }
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Entity::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn position(&self) -> Option<&'a Vec2I> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Vec2I>(Entity::VT_POSITION, None)}
  }
  #[inline]
  pub fn cargo(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ItemStack<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ItemStack>>>>(Entity::VT_CARGO, None)}
  }
}

impl ::flatbuffers::Verifiable for Entity<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("id", Self::VT_ID, false)?
     .visit_field::<Vec2I>("position", Self::VT_POSITION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<ItemStack>>>>("cargo", Self::VT_CARGO, false)?
     .finish();
    Ok(())
  }
}
pub struct EntityArgs<'a> {
    pub id: u64,
    pub position: Option<&'a Vec2I>,
    pub cargo: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ItemStack<'a>>>>>,
}
impl<'a> Default for EntityArgs<'a> {
  #[inline]
  fn default() -> Self {
    EntityArgs {
      id: 0,
      position: None,
      cargo: None,
    }
  }
}

pub struct EntityBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> EntityBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: u64) {
    self.fbb_.push_slot::<u64>(Entity::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_position(&mut self, position: &Vec2I) {
    self.fbb_.push_slot_always::<&Vec2I>(Entity::VT_POSITION, position);
  }
  #[inline]
  pub fn add_cargo(&mut self, cargo: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<ItemStack<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Entity::VT_CARGO, cargo);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> EntityBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    EntityBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Entity<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Entity<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Entity");
      ds.field("id", &self.id());
      ds.field("position", &self.position());
      ds.field("cargo", &self.cargo());
      ds.finish()
  }
}
pub enum ComputeBudgetOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ComputeBudget<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ComputeBudget<'a> {
  type Inner = ComputeBudget<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ComputeBudget<'a> {
  pub const VT_CPU_TIME_MS: ::flatbuffers::VOffsetT = 4;
  pub const VT_WALL_TIME_MS: ::flatbuffers::VOffsetT = 6;
  pub const VT_MEMORY_BYTES: ::flatbuffers::VOffsetT = 8;
  pub const VT_STDOUT_BYTES: ::flatbuffers::VOffsetT = 10;
  pub const VT_STDERR_BYTES: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ComputeBudget { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ComputeBudgetArgs
  ) -> ::flatbuffers::WIPOffset<ComputeBudget<'bldr>> {
    let mut builder = ComputeBudgetBuilder::new(_fbb);
    builder.add_stderr_bytes(args.stderr_bytes);
    builder.add_stdout_bytes(args.stdout_bytes);
    builder.add_memory_bytes(args.memory_bytes);
    builder.add_wall_time_ms(args.wall_time_ms);
    builder.add_cpu_time_ms(args.cpu_time_ms);
    builder.finish()
  }


  #[inline]
  pub fn cpu_time_ms(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ComputeBudget::VT_CPU_TIME_MS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn wall_time_ms(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ComputeBudget::VT_WALL_TIME_MS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn memory_bytes(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ComputeBudget::VT_MEMORY_BYTES, Some(0)).unwrap()}
  }
  #[inline]
  pub fn stdout_bytes(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ComputeBudget::VT_STDOUT_BYTES, Some(0)).unwrap()}
  }
  #[inline]
  pub fn stderr_bytes(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ComputeBudget::VT_STDERR_BYTES, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for ComputeBudget<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("cpu_time_ms", Self::VT_CPU_TIME_MS, false)?
     .visit_field::<u32>("wall_time_ms", Self::VT_WALL_TIME_MS, false)?
     .visit_field::<u32>("memory_bytes", Self::VT_MEMORY_BYTES, false)?
     .visit_field::<u32>("stdout_bytes", Self::VT_STDOUT_BYTES, false)?
     .visit_field::<u32>("stderr_bytes", Self::VT_STDERR_BYTES, false)?
     .finish();
    Ok(())
  }
}
pub struct ComputeBudgetArgs {
    pub cpu_time_ms: u32,
    pub wall_time_ms: u32,
    pub memory_bytes: u32,
    pub stdout_bytes: u32,
    pub stderr_bytes: u32,
}
impl<'a> Default for ComputeBudgetArgs {
  #[inline]
  fn default() -> Self {
    ComputeBudgetArgs {
      cpu_time_ms: 0,
      wall_time_ms: 0,
      memory_bytes: 0,
      stdout_bytes: 0,
      stderr_bytes: 0,
    }
  }
}

pub struct ComputeBudgetBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ComputeBudgetBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_cpu_time_ms(&mut self, cpu_time_ms: u32) {
    self.fbb_.push_slot::<u32>(ComputeBudget::VT_CPU_TIME_MS, cpu_time_ms, 0);
  }
  #[inline]
  pub fn add_wall_time_ms(&mut self, wall_time_ms: u32) {
    self.fbb_.push_slot::<u32>(ComputeBudget::VT_WALL_TIME_MS, wall_time_ms, 0);
  }
  #[inline]
  pub fn add_memory_bytes(&mut self, memory_bytes: u32) {
    self.fbb_.push_slot::<u32>(ComputeBudget::VT_MEMORY_BYTES, memory_bytes, 0);
  }
  #[inline]
  pub fn add_stdout_bytes(&mut self, stdout_bytes: u32) {
    self.fbb_.push_slot::<u32>(ComputeBudget::VT_STDOUT_BYTES, stdout_bytes, 0);
  }
  #[inline]
  pub fn add_stderr_bytes(&mut self, stderr_bytes: u32) {
    self.fbb_.push_slot::<u32>(ComputeBudget::VT_STDERR_BYTES, stderr_bytes, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ComputeBudgetBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ComputeBudgetBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ComputeBudget<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ComputeBudget<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ComputeBudget");
      ds.field("cpu_time_ms", &self.cpu_time_ms());
      ds.field("wall_time_ms", &self.wall_time_ms());
      ds.field("memory_bytes", &self.memory_bytes());
      ds.field("stdout_bytes", &self.stdout_bytes());
      ds.field("stderr_bytes", &self.stderr_bytes());
      ds.finish()
  }
}
pub enum ActionLimitsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ActionLimits<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ActionLimits<'a> {
  type Inner = ActionLimits<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ActionLimits<'a> {
  pub const VT_MAX_ACTIONS: ::flatbuffers::VOffsetT = 4;
  pub const VT_MAX_PERSISTENT_MEMORY_BYTES: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ActionLimits { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ActionLimitsArgs
  ) -> ::flatbuffers::WIPOffset<ActionLimits<'bldr>> {
    let mut builder = ActionLimitsBuilder::new(_fbb);
    builder.add_max_persistent_memory_bytes(args.max_persistent_memory_bytes);
    builder.add_max_actions(args.max_actions);
    builder.finish()
  }


  #[inline]
  pub fn max_actions(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ActionLimits::VT_MAX_ACTIONS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn max_persistent_memory_bytes(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ActionLimits::VT_MAX_PERSISTENT_MEMORY_BYTES, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for ActionLimits<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("max_actions", Self::VT_MAX_ACTIONS, false)?
     .visit_field::<u32>("max_persistent_memory_bytes", Self::VT_MAX_PERSISTENT_MEMORY_BYTES, false)?
     .finish();
    Ok(())
  }
}
pub struct ActionLimitsArgs {
    pub max_actions: u32,
    pub max_persistent_memory_bytes: u32,
}
impl<'a> Default for ActionLimitsArgs {
  #[inline]
  fn default() -> Self {
    ActionLimitsArgs {
      max_actions: 0,
      max_persistent_memory_bytes: 0,
    }
  }
}

pub struct ActionLimitsBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ActionLimitsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_max_actions(&mut self, max_actions: u32) {
    self.fbb_.push_slot::<u32>(ActionLimits::VT_MAX_ACTIONS, max_actions, 0);
  }
  #[inline]
  pub fn add_max_persistent_memory_bytes(&mut self, max_persistent_memory_bytes: u32) {
    self.fbb_.push_slot::<u32>(ActionLimits::VT_MAX_PERSISTENT_MEMORY_BYTES, max_persistent_memory_bytes, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ActionLimitsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ActionLimitsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ActionLimits<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ActionLimits<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ActionLimits");
      ds.field("max_actions", &self.max_actions());
      ds.field("max_persistent_memory_bytes", &self.max_persistent_memory_bytes());
      ds.finish()
  }
}
}  // pub mod RandGame

