// automatically generated by the FlatBuffers compiler, do not modify
// @generated

use crate::game_common_generated::*;
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod rand_game {

  use crate::game_common_generated::*;
extern crate alloc;

pub enum WorldInfoOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct WorldInfo<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for WorldInfo<'a> {
  type Inner = WorldInfo<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> WorldInfo<'a> {
  pub const VT_TICK: ::flatbuffers::VOffsetT = 4;
  pub const VT_MAP_ID: ::flatbuffers::VOffsetT = 6;
  pub const VT_MAP_KIND: ::flatbuffers::VOffsetT = 8;
  pub const VT_RULESET_VERSION: ::flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    WorldInfo { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args WorldInfoArgs
  ) -> ::flatbuffers::WIPOffset<WorldInfo<'bldr>> {
    let mut builder = WorldInfoBuilder::new(_fbb);
    builder.add_tick(args.tick);
    builder.add_ruleset_version(args.ruleset_version);
    builder.add_map_id(args.map_id);
    builder.add_map_kind(args.map_kind);
    builder.finish()
  }


  #[inline]
  pub fn tick(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(WorldInfo::VT_TICK, Some(0)).unwrap()}
  }
  #[inline]
  pub fn map_id(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(WorldInfo::VT_MAP_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn map_kind(&self) -> MapKind {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<MapKind>(WorldInfo::VT_MAP_KIND, Some(MapKind::Resource)).unwrap()}
  }
  #[inline]
  pub fn ruleset_version(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(WorldInfo::VT_RULESET_VERSION, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for WorldInfo<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("tick", Self::VT_TICK, false)?
     .visit_field::<u32>("map_id", Self::VT_MAP_ID, false)?
     .visit_field::<MapKind>("map_kind", Self::VT_MAP_KIND, false)?
     .visit_field::<u32>("ruleset_version", Self::VT_RULESET_VERSION, false)?
     .finish();
    Ok(())
  }
}
pub struct WorldInfoArgs {
    pub tick: u64,
    pub map_id: u32,
    pub map_kind: MapKind,
    pub ruleset_version: u32,
}
impl<'a> Default for WorldInfoArgs {
  #[inline]
  fn default() -> Self {
    WorldInfoArgs {
      tick: 0,
      map_id: 0,
      map_kind: MapKind::Resource,
      ruleset_version: 0,
    }
  }
}

pub struct WorldInfoBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> WorldInfoBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_tick(&mut self, tick: u64) {
    self.fbb_.push_slot::<u64>(WorldInfo::VT_TICK, tick, 0);
  }
  #[inline]
  pub fn add_map_id(&mut self, map_id: u32) {
    self.fbb_.push_slot::<u32>(WorldInfo::VT_MAP_ID, map_id, 0);
  }
  #[inline]
  pub fn add_map_kind(&mut self, map_kind: MapKind) {
    self.fbb_.push_slot::<MapKind>(WorldInfo::VT_MAP_KIND, map_kind, MapKind::Resource);
  }
  #[inline]
  pub fn add_ruleset_version(&mut self, ruleset_version: u32) {
    self.fbb_.push_slot::<u32>(WorldInfo::VT_RULESET_VERSION, ruleset_version, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> WorldInfoBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    WorldInfoBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<WorldInfo<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for WorldInfo<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("WorldInfo");
      ds.field("tick", &self.tick());
      ds.field("map_id", &self.map_id());
      ds.field("map_kind", &self.map_kind());
      ds.field("ruleset_version", &self.ruleset_version());
      ds.finish()
  }
}
pub enum ObservationOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Observation<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Observation<'a> {
  type Inner = Observation<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Observation<'a> {
  pub const VT_CENTER: ::flatbuffers::VOffsetT = 4;
  pub const VT_RADIUS: ::flatbuffers::VOffsetT = 6;
  pub const VT_VISIBLE_TILES: ::flatbuffers::VOffsetT = 8;
  pub const VT_OWNED_ENTITIES: ::flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Observation { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ObservationArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Observation<'bldr>> {
    let mut builder = ObservationBuilder::new(_fbb);
    if let Some(x) = args.owned_entities { builder.add_owned_entities(x); }
    if let Some(x) = args.visible_tiles { builder.add_visible_tiles(x); }
    builder.add_radius(args.radius);
    if let Some(x) = args.center { builder.add_center(x); }
    builder.finish()
  }


  #[inline]
  pub fn center(&self) -> Option<&'a Vec2I> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Vec2I>(Observation::VT_CENTER, None)}
  }
  #[inline]
  pub fn radius(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Observation::VT_RADIUS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn visible_tiles(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Tile<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Tile>>>>(Observation::VT_VISIBLE_TILES, None)}
  }
  #[inline]
  pub fn owned_entities(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Entity<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Entity>>>>(Observation::VT_OWNED_ENTITIES, None)}
  }
}

impl ::flatbuffers::Verifiable for Observation<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<Vec2I>("center", Self::VT_CENTER, false)?
     .visit_field::<u32>("radius", Self::VT_RADIUS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Tile>>>>("visible_tiles", Self::VT_VISIBLE_TILES, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Entity>>>>("owned_entities", Self::VT_OWNED_ENTITIES, false)?
     .finish();
    Ok(())
  }
}
pub struct ObservationArgs<'a> {
    pub center: Option<&'a Vec2I>,
    pub radius: u32,
    pub visible_tiles: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Tile<'a>>>>>,
    pub owned_entities: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Entity<'a>>>>>,
}
impl<'a> Default for ObservationArgs<'a> {
  #[inline]
  fn default() -> Self {
    ObservationArgs {
      center: None,
      radius: 0,
      visible_tiles: None,
      owned_entities: None,
    }
  }
}

pub struct ObservationBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ObservationBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_center(&mut self, center: &Vec2I) {
    self.fbb_.push_slot_always::<&Vec2I>(Observation::VT_CENTER, center);
  }
  #[inline]
  pub fn add_radius(&mut self, radius: u32) {
    self.fbb_.push_slot::<u32>(Observation::VT_RADIUS, radius, 0);
  }
  #[inline]
  pub fn add_visible_tiles(&mut self, visible_tiles: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Tile<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Observation::VT_VISIBLE_TILES, visible_tiles);
  }
  #[inline]
  pub fn add_owned_entities(&mut self, owned_entities: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Entity<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Observation::VT_OWNED_ENTITIES, owned_entities);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ObservationBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ObservationBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Observation<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Observation<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Observation");
      ds.field("center", &self.center());
      ds.field("radius", &self.radius());
      ds.field("visible_tiles", &self.visible_tiles());
      ds.field("owned_entities", &self.owned_entities());
      ds.finish()
  }
}
pub enum RuntimeLimitsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RuntimeLimits<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for RuntimeLimits<'a> {
  type Inner = RuntimeLimits<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> RuntimeLimits<'a> {
  pub const VT_COMPUTE_BUDGET: ::flatbuffers::VOffsetT = 4;
  pub const VT_ACTION_LIMITS: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    RuntimeLimits { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RuntimeLimitsArgs<'args>
  ) -> ::flatbuffers::WIPOffset<RuntimeLimits<'bldr>> {
    let mut builder = RuntimeLimitsBuilder::new(_fbb);
    if let Some(x) = args.action_limits { builder.add_action_limits(x); }
    if let Some(x) = args.compute_budget { builder.add_compute_budget(x); }
    builder.finish()
  }


  #[inline]
  pub fn compute_budget(&self) -> Option<ComputeBudget<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<ComputeBudget>>(RuntimeLimits::VT_COMPUTE_BUDGET, None)}
  }
  #[inline]
  pub fn action_limits(&self) -> Option<ActionLimits<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<ActionLimits>>(RuntimeLimits::VT_ACTION_LIMITS, None)}
  }
}

impl ::flatbuffers::Verifiable for RuntimeLimits<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<ComputeBudget>>("compute_budget", Self::VT_COMPUTE_BUDGET, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<ActionLimits>>("action_limits", Self::VT_ACTION_LIMITS, false)?
     .finish();
    Ok(())
  }
}
pub struct RuntimeLimitsArgs<'a> {
    pub compute_budget: Option<::flatbuffers::WIPOffset<ComputeBudget<'a>>>,
    pub action_limits: Option<::flatbuffers::WIPOffset<ActionLimits<'a>>>,
}
impl<'a> Default for RuntimeLimitsArgs<'a> {
  #[inline]
  fn default() -> Self {
    RuntimeLimitsArgs {
      compute_budget: None,
      action_limits: None,
    }
  }
}

pub struct RuntimeLimitsBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> RuntimeLimitsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_compute_budget(&mut self, compute_budget: ::flatbuffers::WIPOffset<ComputeBudget<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<ComputeBudget>>(RuntimeLimits::VT_COMPUTE_BUDGET, compute_budget);
  }
  #[inline]
  pub fn add_action_limits(&mut self, action_limits: ::flatbuffers::WIPOffset<ActionLimits<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<ActionLimits>>(RuntimeLimits::VT_ACTION_LIMITS, action_limits);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> RuntimeLimitsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RuntimeLimitsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<RuntimeLimits<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for RuntimeLimits<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("RuntimeLimits");
      ds.field("compute_budget", &self.compute_budget());
      ds.field("action_limits", &self.action_limits());
      ds.finish()
  }
}
pub enum GameInputOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct GameInput<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for GameInput<'a> {
  type Inner = GameInput<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> GameInput<'a> {
  pub const VT_PROTOCOL_VERSION: ::flatbuffers::VOffsetT = 4;
  pub const VT_WORLD: ::flatbuffers::VOffsetT = 6;
  pub const VT_OBSERVATION: ::flatbuffers::VOffsetT = 8;
  pub const VT_PERSISTENT_MEMORY: ::flatbuffers::VOffsetT = 10;
  pub const VT_RUNTIME_LIMITS: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    GameInput { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args GameInputArgs<'args>
  ) -> ::flatbuffers::WIPOffset<GameInput<'bldr>> {
    let mut builder = GameInputBuilder::new(_fbb);
    if let Some(x) = args.runtime_limits { builder.add_runtime_limits(x); }
    if let Some(x) = args.persistent_memory { builder.add_persistent_memory(x); }
    if let Some(x) = args.observation { builder.add_observation(x); }
    if let Some(x) = args.world { builder.add_world(x); }
    builder.add_protocol_version(args.protocol_version);
    builder.finish()
  }


  #[inline]
  pub fn protocol_version(&self) -> ProtocolVersion {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<ProtocolVersion>(GameInput::VT_PROTOCOL_VERSION, Some(ProtocolVersion::V1)).unwrap()}
  }
  #[inline]
  pub fn world(&self) -> Option<WorldInfo<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<WorldInfo>>(GameInput::VT_WORLD, None)}
  }
  #[inline]
  pub fn observation(&self) -> Option<Observation<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<Observation>>(GameInput::VT_OBSERVATION, None)}
  }
  #[inline]
  pub fn persistent_memory(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(GameInput::VT_PERSISTENT_MEMORY, None)}
  }
  #[inline]
  pub fn runtime_limits(&self) -> Option<RuntimeLimits<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<RuntimeLimits>>(GameInput::VT_RUNTIME_LIMITS, None)}
  }
}

impl ::flatbuffers::Verifiable for GameInput<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<ProtocolVersion>("protocol_version", Self::VT_PROTOCOL_VERSION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<WorldInfo>>("world", Self::VT_WORLD, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<Observation>>("observation", Self::VT_OBSERVATION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("persistent_memory", Self::VT_PERSISTENT_MEMORY, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<RuntimeLimits>>("runtime_limits", Self::VT_RUNTIME_LIMITS, false)?
     .finish();
    Ok(())
  }
}
pub struct GameInputArgs<'a> {
    pub protocol_version: ProtocolVersion,
    pub world: Option<::flatbuffers::WIPOffset<WorldInfo<'a>>>,
    pub observation: Option<::flatbuffers::WIPOffset<Observation<'a>>>,
    pub persistent_memory: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub runtime_limits: Option<::flatbuffers::WIPOffset<RuntimeLimits<'a>>>,
}
impl<'a> Default for GameInputArgs<'a> {
  #[inline]
  fn default() -> Self {
    GameInputArgs {
      protocol_version: ProtocolVersion::V1,
      world: None,
      observation: None,
      persistent_memory: None,
      runtime_limits: None,
    }
  }
}

pub struct GameInputBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> GameInputBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_protocol_version(&mut self, protocol_version: ProtocolVersion) {
    self.fbb_.push_slot::<ProtocolVersion>(GameInput::VT_PROTOCOL_VERSION, protocol_version, ProtocolVersion::V1);
  }
  #[inline]
  pub fn add_world(&mut self, world: ::flatbuffers::WIPOffset<WorldInfo<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<WorldInfo>>(GameInput::VT_WORLD, world);
  }
  #[inline]
  pub fn add_observation(&mut self, observation: ::flatbuffers::WIPOffset<Observation<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<Observation>>(GameInput::VT_OBSERVATION, observation);
  }
  #[inline]
  pub fn add_persistent_memory(&mut self, persistent_memory: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(GameInput::VT_PERSISTENT_MEMORY, persistent_memory);
  }
  #[inline]
  pub fn add_runtime_limits(&mut self, runtime_limits: ::flatbuffers::WIPOffset<RuntimeLimits<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<RuntimeLimits>>(GameInput::VT_RUNTIME_LIMITS, runtime_limits);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> GameInputBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    GameInputBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<GameInput<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for GameInput<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("GameInput");
      ds.field("protocol_version", &self.protocol_version());
      ds.field("world", &self.world());
      ds.field("observation", &self.observation());
      ds.field("persistent_memory", &self.persistent_memory());
      ds.field("runtime_limits", &self.runtime_limits());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `GameInput`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_game_input_unchecked`.
pub fn root_as_game_input(buf: &[u8]) -> Result<GameInput<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<GameInput>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `GameInput` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_game_input_unchecked`.
pub fn size_prefixed_root_as_game_input(buf: &[u8]) -> Result<GameInput<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<GameInput>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `GameInput` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_game_input_unchecked`.
pub fn root_as_game_input_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<GameInput<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<GameInput<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `GameInput` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_game_input_unchecked`.
pub fn size_prefixed_root_as_game_input_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<GameInput<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<GameInput<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a GameInput and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `GameInput`.
pub unsafe fn root_as_game_input_unchecked(buf: &[u8]) -> GameInput<'_> {
  unsafe { ::flatbuffers::root_unchecked::<GameInput>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed GameInput and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `GameInput`.
pub unsafe fn size_prefixed_root_as_game_input_unchecked(buf: &[u8]) -> GameInput<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<GameInput>(buf) }
}
pub const GAME_INPUT_IDENTIFIER: &str = "BWI1";

#[inline]
pub fn game_input_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, GAME_INPUT_IDENTIFIER, false)
}

#[inline]
pub fn game_input_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, GAME_INPUT_IDENTIFIER, true)
}

#[inline]
pub fn finish_game_input_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<GameInput<'a>>) {
  fbb.finish(root, Some(GAME_INPUT_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_game_input_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<GameInput<'a>>) {
  fbb.finish_size_prefixed(root, Some(GAME_INPUT_IDENTIFIER));
}
}  // pub mod RandGame

