use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

#[derive(Debug, serde::Deserialize)]
struct BuildingCatalog {
    buildings: Vec<BuildingSpec>,
}

#[derive(Debug, serde::Deserialize)]
struct BuildingSpec {
    name: String,
    id: String,
    crafting_time: Option<u32>,
    mining_time: Option<u32>,
    smelting_time: Option<u32>,
    electricity: Option<i32>,
    energy: Option<i32>,
    module_slot: Option<u32>,
    width: u32,
    capacity: Option<u32>,
}

#[derive(Debug, serde::Deserialize)]
struct RecipeCatalog {
    recipes: Vec<RecipeSpec>,
}

#[derive(Debug, serde::Deserialize)]
struct RecipeSpec {
    name: String,
    id: String,
    max_stack: u32,
    building: Vec<String>,
    inputs: Vec<ItemStackSpec>,
    crafting_time: u32,
    outputs: Vec<ItemStackSpec>,
}

#[derive(Debug, serde::Deserialize)]
struct ResearchCatalog {
    researches: Vec<ResearchSpec>,
}

#[derive(Debug, serde::Deserialize)]
struct ResearchSpec {
    name: String,
    id: String,
    inputs: Vec<ItemStackSpec>,
    unlocked_recipes: Vec<String>,
}

#[derive(Debug, serde::Deserialize)]
struct ItemStackSpec {
    kind: String,
    amount: u32,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let workspace_dir = manifest_dir
        .parent()
        .and_then(|path| path.parent())
        .expect("workspace dir");
    let building_path = workspace_dir.join("config/building.yaml");
    let recipe_path = workspace_dir.join("config/recipe.yaml");
    let research_path = workspace_dir.join("config/research.yaml");

    println!("cargo:rerun-if-changed={}", building_path.display());
    println!("cargo:rerun-if-changed={}", recipe_path.display());
    println!("cargo:rerun-if-changed={}", research_path.display());

    let buildings = read_yaml::<BuildingCatalog>(&building_path);
    let recipes = read_yaml::<RecipeCatalog>(&recipe_path);
    let researches = read_yaml::<ResearchCatalog>(&research_path);
    let output = generate_rules(&buildings, &recipes, &researches);
    let generated_dir = manifest_dir.join("src/generated");
    fs::create_dir_all(&generated_dir).expect("create generated dir");
    let generated_path = generated_dir.join("rules.rs");
    fs::write(&generated_path, output).expect("write generated rules");
    let status = Command::new("rustfmt")
        .arg(&generated_path)
        .status()
        .expect("run rustfmt for generated rules");
    assert!(status.success(), "rustfmt failed for generated rules");
}

fn read_yaml<T>(path: &PathBuf) -> T
where
    T: serde::de::DeserializeOwned,
{
    let input = fs::read_to_string(path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
    serde_yaml::from_str(&input)
        .unwrap_or_else(|err| panic!("failed to parse {}: {err}", path.display()))
}

fn generate_rules(
    buildings: &BuildingCatalog,
    recipes: &RecipeCatalog,
    researches: &ResearchCatalog,
) -> String {
    let mut output = String::new();
    output.push_str("// @generated by crates/common/build.rs from config/*.yaml\n");
    output.push_str(
        "// Do not edit by hand. Edit config/building.yaml or config/recipe.yaml instead.\n\n",
    );
    output.push_str("use crate::rules::validate_rule_catalog;\n");
    output.push_str(
        "use crate::rules::{BuildingCatalog, BuildingSpec, ItemStackSpec, RecipeCatalog, RecipeSpec, ResearchCatalog, ResearchSpec, RuleCatalog};\n\n",
    );
    output.push_str("pub fn default_rule_catalog() -> RuleCatalog {\n");
    output.push_str("    let catalog = RuleCatalog {\n");
    output.push_str("        buildings: BuildingCatalog { buildings: vec![\n");
    for building in &buildings.buildings {
        output.push_str("            BuildingSpec {\n");
        push_string(&mut output, "name", &building.name, 16);
        push_string(&mut output, "id", &building.id, 16);
        push_option_u32(&mut output, "crafting_time", building.crafting_time, 16);
        push_option_u32(&mut output, "mining_time", building.mining_time, 16);
        push_option_u32(&mut output, "smelting_time", building.smelting_time, 16);
        push_option_i32(&mut output, "electricity", building.electricity, 16);
        push_option_i32(&mut output, "energy", building.energy, 16);
        push_option_u32(&mut output, "module_slot", building.module_slot, 16);
        output.push_str(&format!("                width: {},\n", building.width));
        push_option_u32(&mut output, "capacity", building.capacity, 16);
        output.push_str("            },\n");
    }
    output.push_str("        ] },\n");
    output.push_str("        recipes: RecipeCatalog { recipes: vec![\n");
    for recipe in &recipes.recipes {
        output.push_str("            RecipeSpec {\n");
        push_string(&mut output, "name", &recipe.name, 16);
        push_string(&mut output, "id", &recipe.id, 16);
        output.push_str(&format!(
            "                max_stack: {},\n",
            recipe.max_stack
        ));
        push_string_vec(&mut output, "building", &recipe.building, 16);
        push_stack_vec(&mut output, "inputs", &recipe.inputs, 16);
        output.push_str(&format!(
            "                crafting_time: {},\n",
            recipe.crafting_time
        ));
        push_stack_vec(&mut output, "outputs", &recipe.outputs, 16);
        output.push_str("            },\n");
    }
    output.push_str("        ] },\n");
    output.push_str("        researches: ResearchCatalog { researches: vec![\n");
    for research in &researches.researches {
        output.push_str("            ResearchSpec {\n");
        push_string(&mut output, "name", &research.name, 16);
        push_string(&mut output, "id", &research.id, 16);
        push_stack_vec(&mut output, "inputs", &research.inputs, 16);
        push_string_vec(
            &mut output,
            "unlocked_recipes",
            &research.unlocked_recipes,
            16,
        );
        output.push_str("            },\n");
    }
    output.push_str("        ] },\n");
    output.push_str("    };\n");
    output.push_str(
        "    validate_rule_catalog(&catalog).expect(\"generated rule catalog must be valid\");\n",
    );
    output.push_str("    catalog\n");
    output.push_str("}\n");
    output
}

fn push_string(output: &mut String, field: &str, value: &str, indent: usize) {
    output.push_str(&format!(
        "{}{}: {:?}.into(),\n",
        " ".repeat(indent),
        field,
        value
    ));
}

fn push_option_u32(output: &mut String, field: &str, value: Option<u32>, indent: usize) {
    output.push_str(&format!(
        "{}{}: {},\n",
        " ".repeat(indent),
        field,
        option_u32(value)
    ));
}

fn push_option_i32(output: &mut String, field: &str, value: Option<i32>, indent: usize) {
    output.push_str(&format!(
        "{}{}: {},\n",
        " ".repeat(indent),
        field,
        option_i32(value)
    ));
}

fn push_string_vec(output: &mut String, field: &str, values: &[String], indent: usize) {
    let values = values
        .iter()
        .map(|value| format!("{:?}.into()", value))
        .collect::<Vec<_>>()
        .join(", ");
    output.push_str(&format!(
        "{}{}: vec![{}],\n",
        " ".repeat(indent),
        field,
        values
    ));
}

fn push_stack_vec(output: &mut String, field: &str, values: &[ItemStackSpec], indent: usize) {
    let values = values
        .iter()
        .map(|value| {
            format!(
                "ItemStackSpec {{ kind: {:?}.into(), amount: {} }}",
                value.kind, value.amount
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    output.push_str(&format!(
        "{}{}: vec![{}],\n",
        " ".repeat(indent),
        field,
        values
    ));
}

fn option_u32(value: Option<u32>) -> String {
    value.map_or_else(|| "None".into(), |value| format!("Some({value})"))
}

fn option_i32(value: Option<i32>) -> String {
    value.map_or_else(|| "None".into(), |value| format!("Some({value})"))
}
