name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: fmt
        run: cargo fmt --check

      - name: check
        run: cargo check

      - name: build
        run: cargo build --workspace

      - name: test
        run: cargo test

      - name: clippy
        run: cargo clippy --all-targets --workspace -- -D warnings
